name: netlib

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        feature:
          - static
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: apt install gfortran
        run: |
          sudo apt update
          sudo apt install -y gfortran
      - name: cargo test
        run: cargo test --manifest-path=ndarray-linalg/Cargo.toml --no-default-features --features=netlib-${{ matrix.feature }}
