name: openblas

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  linux:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        feature:
          - static
          - system
    steps:
      - uses: actions/checkout@v4
      - name: apt install gfortran
        run: |
          apt update
          apt install -y gfortran
      - name: Install OpenBLAS by apt
        run: |
          apt update
          apt install -y libopenblas-dev
        if: ${{ contains(matrix.feature, 'system') }}
      - name: cargo test
        run: cargo test --manifest-path=ndarray-linalg/Cargo.toml --no-default-features --features=openblas-${{ matrix.feature }}
