name: Rust

on:
  push:
    branches:
      - master
  pull_request: {}
  workflow_dispatch:

jobs:
  check-format:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: fmt
      run: cargo fmt -- --check

  check:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: cargo check
      run: cargo check --all-targets

  check-doc:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: cargo doc
      run: cargo doc --no-deps

  clippy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: cargo clippy
      run: cargo clippy

  coverage:
    runs-on: ubuntu-22.04
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - name: Install Cross
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-tarpaulin
      - name: Generate code coverage
        run: cargo +nightly tarpaulin --features=intel-mkl-system -workspace --out xml
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v5
